### ISSUE TITLE
ninja-ide not executable after install

### ISSUE THREAD

**Issue by orcus-de** [linuxmint/mint19.2-beta#40]
**Describe the bug**
using  installed  + 19.2 cinnamon 64bit beta    qemu/kvm vm
Installed without additional codecs
fully updated   2019-07-20

ninja-ide not working after installation

**To Reproduce**
1) Install ninja-ide using software-manager
2) launch it via menu - no reaction
======================
launching ninja-ide from a terminal does show:

oadm@mint-19-2-cinnamon-64bit-beta:~$ ninja-ide 
Traceback (most recent call last):
  File "/usr/bin/ninja-ide", line 34, in <module>
    ninja_ide.setup_and_run()
  File "/usr/lib/python2.7/dist-packages/ninja_ide/__init__.py", line 71, in setup_and_run
    core.run_ninja()
  File "/usr/lib/python2.7/dist-packages/ninja_ide/core/core.py", line 48, in run_ninja
    from ninja_ide.gui import ide
  File "/usr/lib/python2.7/dist-packages/ninja_ide/gui/ide.py", line 45, in <module>
    from ninja_ide.core import plugin_services
  File "/usr/lib/python2.7/dist-packages/ninja_ide/core/plugin_services.py", line 29, in <module>
    from ninja_ide.gui.main_panel import main_container
  File "/usr/lib/python2.7/dist-packages/ninja_ide/gui/main_panel/main_container.py", line 36, in <module>
    from ninja_ide.gui.main_panel import tab_widget
  File "/usr/lib/python2.7/dist-packages/ninja_ide/gui/main_panel/tab_widget.py", line 40, in <module>
    from ninja_ide.gui.main_panel import browser_widget
  File "/usr/lib/python2.7/dist-packages/ninja_ide/gui/main_panel/browser_widget.py", line 27, in <module>
    from PyQt4.QtWebKit import QWebView
ImportError: No module named QtWebKit

**Expected behavior**
ninja-ide should work (or not being offered at all)
required dependencies should be resolved/installed

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**

**Locale:**
Paste the output of `locale`.

**Drivers:**
Paste the output of `inxi -Gxx`.

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**

**Comment by clefebvre** [comment]
That's upstream from us @orcus-de: https://github.com/ninja-ide/ninja-ide/issues/1985.
